# Site settings
title: Curtis Bridges
email: curtis@curtisbridges.com
description: > # this means to ignore newlines until "baseurl:"
    Software, Development,
    Learning, Reading, Writing,
    Photography, and Sports

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://curtisbridges.com" # the base hostname & protocol for your site
#url: https://curtisbridges.com
#enforce_ssl: curtisbridges.com

permalink: pretty
twitter_username: curtisbridges
github_username:  curtisbridges

# Build settings
markdown: kramdown
