baseURL = "http://curtisbridges.com/"
languageCode = "en-us"
title = "Curtis Bridges"
theme = ""
publishDir = "docs"

[params]
    author = "Curtis Bridges"
    description = "Freelance iOS and web developer from New Hampshire."
    githubUsername = "curtisbridges"
    accent = "#ff3300"
    showBorder = true
    backgroundColor = "#ffffff"
    font = "Open Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atom-one-dark"
    highlightLanguages = ["java", "javascript", "json", "typescript", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/product/"
    name = "Products"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:curtis@curtisbridges.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/curtisbridges/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://github.com/curtisbridges/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/curtisbridges/"
    name = "linkedin"
    weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
