languageCode = "en-us"
title = "Curtis Bridges"
baseurl = "http://curtisbridges.com/blog/"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://curtisbridges.com\">Curtis Bridges</a> 2017"
#disqusShortname = "shortname"
googleAnalytics = "UA-15421339-1"
description = "Independent iOS developer in New Hampshire"
keywords = ["developer", "curtis", "bridges", ""]

[taxonomies]
tag = "tags"
category = "categories"

[params]
Author = "Curtis Bridges"

# [params.highlight]
# style = "github"
# languages = ["go", "dockerfile"]

[[params.social]]
url = "https://twitter.com/curtisbridges"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://github.com/curtisbridges"
fa_icon = "fa-github"

[[params.social]]
url = "http://linkedin.com/in/curtisbridges/"
fa_icon = "fa-linkedin"

# [[params.social]]
# url = "https://gitlab.com/curtisbridges"
# fa_icon = "fa-gitlab"

# [[params.social]]
# url = "https://telegram.me/beli3ver"
# fa_icon = "fa-telegram"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
